### ISSUE TITLE
Pimoroni pan tilt hat

### ISSUE THREAD

**Issue by kirstm** [luetzel/motion_eye_servo_action#2]
Hi, what a great feature for motioneye!

I would love to get this working with my pimoroni pantilt hat! 

Any chance to get som help with that? I am too new to python and don´t know where to start, I know I ask alot of you but if you have the time and will to have a look at the schematics  to see if there is an easy fix, I would be extremely grateful!

Pin out Pantitlhat
https://pinout.xyz/pinout/pan_tilt_hat#

Pan tilt hat user manual
http://docs.pimoroni.com/pantilthat/#pan
https://www.waveshare.com/w/upload/b/b9/Pan-Tilt_HAT_user_manual_en.pdf

For example, when i run your code without any changes with `python3 left_1` I get,
```
File "left_1", line 25
    print horz_pos
                 ^
SyntaxError: Missing parentheses in call to 'print'

```

and `python left_1` will get me
```
Traceback (most recent call last):
  File "left_1", line 17, in <module>
    pwm = Adafruit_PCA9685.PCA9685()
  File "build/bdist.linux-armv7l/egg/Adafruit_PCA9685/PCA9685.py", line 75, in __init__
  File "build/bdist.linux-armv7l/egg/Adafruit_PCA9685/PCA9685.py", line 111, in set_all_pwm
  File "build/bdist.linux-armv7l/egg/Adafruit_GPIO/I2C.py", line 116, in write8
  File "build/bdist.linux-armv7l/egg/Adafruit_PureIO/smbus.py", line 256, in write_byte_data
IOError: [Errno 121] Remote I/O error``
```

Again, I know I ask alot of you, but if you can point me in the right direction I would be very grateful!

Thanks!

/Kirst

**Comment by luetzel** [comment]
Hi Kirst,
my python scripts were not ported, yet, to python 3, that's why it complains about missing parentheses in call to print.
`print(horz_pos) `
should fix this problem. Since you want to use the Pimoroni HAT, you have to download and install the the pantilthat module, instead of Adafruit_PCA9685. Have a look at this example on how to pan and tilt your camera: https://github.com/pimoroni/pantilt-hat/blob/master/examples/smooth.py The Pimoroni HAT also supports a timeout 
`pantilthat.idle_timeout(0.5)`
which whill disconnect power from your servos, so that they keep quiet when idle.
Cheers
/luetzel

**Comment by kirstm** [comment]
Great, thanks for your reply!

I tried to import the library in your script, but I understand there are too many other differencies between the controller boards to make it work. For example the pan tilt hat is using i2c for communications where your controller board is using GPIOs(?).. My limited python knowledge can make the hat move to predefined angle, but not pan or tilt continuously as your servos do in your script.. Again, my limited knowledge make it difficult to pick out the nitty gritty out of the `smooth.py` script.. What I can make out of it, is that the hat is told pan and tilt in one long move, not for example pan far right then far left.. if that were the case I might had been able to pick those snippets out use them in Motioneye... Anyhow, you always learn something and that is why it is so fun with this kind of things! 
Thank you for taking your time and answering my question, it made me learn a bit more about these things!
I wish you a happy easter!

/Kirst
